import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getSessionUser, requireTeamRole, isNextResponse } from "@/lib/rbac";
import { ok, unauthorized, badRequest, notFound, conflict, handleError } from "@/lib/api-response";
import { BatchStatus, ShiftStatus, ShiftSource, SwapStatus, TeamRole } from "@/app/generated/prisma/client";
import { generateShifts, computeConfirmationDueAt, TimeSlot } from "@/lib/rotation/engine";
import { scheduleAllRemindersForBatch } from "@/lib/queue/scheduler";
import { writeAuditLog } from "@/lib/audit";

const Schema = z.object({
  fromDate: z.string().datetime(),
});

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ batchId: string }> }
) {
  try {
    const actor = await getSessionUser();
    if (!actor) return unauthorized();

    const { batchId } = await params;
    const body = await req.json();
    const { fromDate: fromDateStr } = Schema.parse(body);
    const fromDate = new Date(fromDateStr);

    const batch = await prisma.scheduleBatch.findUnique({
      where: { id: batchId },
      include: {
        policy: {
          include: {
            team: {
              include: {
                members: {
                  include: { user: { select: { id: true } } },
                  orderBy: { order: "asc" },
                },
              },
            },
          },
        },
      },
    });

    if (!batch) return notFound("Batch not found");
    if (batch.status !== BatchStatus.PUBLISHED) {
      return conflict("Only PUBLISHED batches can be rescheduled", "BATCH_NOT_PUBLISHED");
    }

    const result = await requireTeamRole(batch.policy.teamId, TeamRole.MANAGER);
    if (isNextResponse(result)) return result;

    if (fromDate < batch.rangeStart) {
      return badRequest("fromDate must be within the batch range");
    }
    if (fromDate >= batch.rangeEnd) {
      return badRequest("fromDate must be before batch rangeEnd");
    }

    // Cannot reschedule past the current date into completed shifts
    const hasActiveOrCompleted = await prisma.shift.count({
      where: {
        batchId,
        startsAt: { gte: fromDate },
        status: { in: [ShiftStatus.ACTIVE, ShiftStatus.COMPLETED] },
      },
    });
    if (hasActiveOrCompleted > 0) {
      return conflict(
        `Cannot reschedule: ${hasActiveOrCompleted} shift(s) on or after fromDate are ACTIVE or COMPLETED`,
        "SHIFTS_ACTIVE"
      );
    }

    // Shifts to remove (future, still PUBLISHED, start >= fromDate)
    const shiftsToRemove = await prisma.shift.findMany({
      where: { batchId, startsAt: { gte: fromDate }, status: ShiftStatus.PUBLISHED },
      select: { id: true },
    });
    const removeIds = shiftsToRemove.map((s) => s.id);

    // Compute startingIndex: count all non-cancelled autogenerated shifts for this policy
    // that start BEFORE fromDate — this continues rotation from the right position.
    const policy = batch.policy;
    const timeSlots = policy.timeSlots as TimeSlot[] | null | undefined;
    const participants = policy.team.members.map((m, i, arr) => ({
      userId: m.user.id,
      backupId: arr[(i + 1) % arr.length].user.id,
    }));

    if (participants.length === 0) {
      return badRequest("Team has no members");
    }

    const keptShiftCount = await prisma.shift.count({
      where: {
        policyId: batch.policyId,
        source: ShiftSource.AUTOGENERATED,
        status: { notIn: [ShiftStatus.CANCELLED] },
        startsAt: { lt: fromDate },
      },
    });

    const slotsPerDay = timeSlots && timeSlots.length > 0 ? timeSlots.length : 1;
    const startingIndex =
      timeSlots && timeSlots.length > 0
        ? Math.floor(keptShiftCount / slotsPerDay) % participants.length
        : keptShiftCount % participants.length;

    // Generate new shifts
    const newShifts = generateShifts(
      { ...policy, timeSlots },
      participants,
      fromDate,
      batch.rangeEnd,
      startingIndex
    ).filter((s) => s.startsAt >= fromDate);

    // Execute in transaction
    await prisma.$transaction(async (tx) => {
      if (removeIds.length > 0) {
        // Cancel open swap requests referencing these shifts
        await tx.swapRequest.updateMany({
          where: {
            status: { in: [SwapStatus.REQUESTED, SwapStatus.ACCEPTED_BY_TARGET] },
            OR: [
              { originalShiftId: { in: removeIds } },
              { targetShiftId: { in: removeIds } },
            ],
          },
          data: { status: SwapStatus.CANCELLED, version: { increment: 1 } },
        });

        // Delete confirmations, tasks, then shifts
        await tx.shiftConfirmation.deleteMany({ where: { shiftId: { in: removeIds } } });
        await tx.shiftTask.deleteMany({ where: { shiftId: { in: removeIds } } });
        await tx.shift.deleteMany({ where: { id: { in: removeIds } } });
      }

      // Create new shifts
      await tx.shift.createMany({
        data: newShifts.map((s) => ({
          policyId: batch.policyId,
          batchId,
          assigneeId: s.assigneeId,
          backupId: s.backupId,
          startsAt: s.startsAt,
          endsAt: s.endsAt,
          status: ShiftStatus.PUBLISHED,
          source: ShiftSource.AUTOGENERATED,
        })),
      });
    });

    // Create confirmations for new shifts
    const createdShifts = await prisma.shift.findMany({
      where: {
        batchId,
        startsAt: { gte: fromDate },
        status: ShiftStatus.PUBLISHED,
      },
      select: { id: true, assigneeId: true, startsAt: true, endsAt: true },
    });

    const now = new Date();
    const minDueAt = new Date(now.getTime() + 60 * 60 * 1000);
    await prisma.shiftConfirmation.createMany({
      data: createdShifts.map((s) => {
        const computed = computeConfirmationDueAt(
          { assigneeId: s.assigneeId, startsAt: s.startsAt, endsAt: s.endsAt },
          policy.confirmationDueHours
        );
        return {
          shiftId: s.id,
          userId: s.assigneeId,
          dueAt: computed < minDueAt ? minDueAt : computed,
        };
      }),
    });

    // Schedule reminders
    const confirmations = await prisma.shiftConfirmation.findMany({
      where: { shift: { batchId, startsAt: { gte: fromDate } } },
      include: { shift: { select: { startsAt: true, endsAt: true } } },
    });

    await scheduleAllRemindersForBatch(
      confirmations.map((c) => ({
        id: c.id,
        shiftId: c.shiftId,
        userId: c.userId,
        dueAt: c.dueAt,
        shift: c.shift,
      })),
      policy
    );

    await writeAuditLog({
      actorId: actor.id,
      entityType: "ScheduleBatch",
      entityId: batchId,
      action: "RESCHEDULE",
      newValue: {
        fromDate: fromDate.toISOString(),
        removedShifts: removeIds.length,
        newShifts: newShifts.length,
      },
      ipAddress: req.headers.get("x-forwarded-for") ?? undefined,
    });

    return ok({
      batchId,
      fromDate: fromDate.toISOString(),
      removedShifts: removeIds.length,
      newShifts: newShifts.length,
    });
  } catch (error) {
    return handleError(error);
  }
}
