import { NextRequest } from "next/server";
import { z } from "zod";
import { startOfDay, subDays } from "date-fns";
import { prisma } from "@/lib/prisma";
import { getSessionUser, requireTeamRole, isNextResponse } from "@/lib/rbac";
import { ok, unauthorized, badRequest, notFound, conflict, handleError } from "@/lib/api-response";
import { BatchStatus, ShiftStatus, ShiftSource, SwapStatus, TeamRole } from "@/app/generated/prisma/client";
import {
  generateShifts,
  computeConfirmationDueAt,
  TimeSlot,
  OccupiedMap,
  PriorState,
  localDayKey,
  isNightShiftTime,
} from "@/lib/rotation/engine";
import { scheduleAllRemindersForBatchSafe } from "@/lib/queue/scheduler";
import { notifyAssigneesScheduleUpdated } from "@/lib/notifications/notify-assignees";
import { writeAuditLog } from "@/lib/audit";

const Schema = z.object({
  fromDate: z.string().min(1),
});

function parseFromDateInput(input: string): Date | null {
  const dateOnlyPattern = /^\d{4}-\d{2}-\d{2}$/;
  if (dateOnlyPattern.test(input)) {
    return startOfDay(new Date(`${input}T00:00:00`));
  }
  const parsed = new Date(input);
  if (Number.isNaN(parsed.getTime())) return null;
  return parsed;
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ batchId: string }> }
) {
  try {
    const actor = await getSessionUser();
    if (!actor) return unauthorized();

    const { batchId } = await params;
    const body = await req.json();
    const { fromDate: fromDateInput } = Schema.parse(body);
    const fromDate = parseFromDateInput(fromDateInput);
    if (!fromDate) return badRequest("fromDate is invalid");
    const now = new Date();
    const cutoff = fromDate > now ? fromDate : now;

    const batch = await prisma.scheduleBatch.findUnique({
      where: { id: batchId },
      include: {
        policy: {
          include: {
            team: {
              include: {
                members: {
                  include: { user: { select: { id: true } } },
                  orderBy: { order: "asc" },
                },
              },
            },
          },
        },
      },
    });

    if (!batch) return notFound("Batch not found");
    if (batch.status !== BatchStatus.PUBLISHED) {
      return conflict("Only PUBLISHED batches can be rescheduled", "BATCH_NOT_PUBLISHED");
    }
    if (!batch.policy.isActive) {
      return conflict("Policy is inactive.", "POLICY_INACTIVE");
    }

    const result = await requireTeamRole(batch.policy.teamId, TeamRole.MANAGER);
    if (isNextResponse(result)) return result;

    if (fromDate < batch.rangeStart) {
      return badRequest("fromDate must be within the batch range");
    }
    if (fromDate >= batch.rangeEnd) {
      return badRequest("fromDate must be before batch rangeEnd");
    }

    // Cannot reschedule past the current date into completed shifts
    const hasActiveOrCompleted = await prisma.shift.count({
      where: {
        batchId,
        startsAt: { gte: cutoff },
        status: { in: [ShiftStatus.ACTIVE, ShiftStatus.COMPLETED] },
      },
    });
    if (hasActiveOrCompleted > 0) {
      return conflict(
        `Cannot reschedule: ${hasActiveOrCompleted} shift(s) on or after fromDate are ACTIVE or COMPLETED`,
        "SHIFTS_ACTIVE"
      );
    }

    // Shifts to remove (future, still PUBLISHED, start >= fromDate)
    const shiftsToRemove = await prisma.shift.findMany({
      where: { batchId, startsAt: { gte: cutoff }, status: ShiftStatus.PUBLISHED },
      select: { id: true },
    });
    const removeIds = shiftsToRemove.map((s) => s.id);

    const policy = batch.policy;
    const timeSlots = policy.timeSlots as TimeSlot[] | null | undefined;
    const participants = policy.team.members.map((m, i, arr) => ({
      userId: m.user.id,
      backupId: arr[(i + 1) % arr.length].user.id,
    }));

    if (participants.length === 0) {
      return badRequest("Team has no members");
    }

    const keptShiftCount = await prisma.shift.count({
      where: {
        policyId: batch.policyId,
        source: ShiftSource.AUTOGENERATED,
        status: { notIn: [ShiftStatus.CANCELLED] },
        startsAt: { lt: cutoff },
      },
    });

    const slotsPerDay = timeSlots && timeSlots.length > 0 ? timeSlots.length : 1;
    const startingIndex =
      timeSlots && timeSlots.length > 0
        ? Math.floor(keptShiftCount / slotsPerDay) % participants.length
        : keptShiftCount % participants.length;

    // Build occupied map: shifts from OTHER policies in the same team within the new range.
    const userIds = participants.map((p) => p.userId);
    const crossPolicyShifts = await prisma.shift.findMany({
      where: {
        policyId: { not: batch.policyId },
        policy: { teamId: policy.teamId },
        assigneeId: { in: userIds },
        status: { in: [ShiftStatus.PUBLISHED, ShiftStatus.ACTIVE] },
        startsAt: { lt: batch.rangeEnd },
        endsAt: { gt: cutoff },
      },
      select: { assigneeId: true, policyId: true, startsAt: true, endsAt: true },
    });

    const occupied: OccupiedMap = new Map();
    for (const s of crossPolicyShifts) {
      const list = occupied.get(s.assigneeId) ?? [];
      list.push({ policyId: s.policyId, startsAt: s.startsAt, endsAt: s.endsAt });
      occupied.set(s.assigneeId, list);
    }

    // Compute prior state from existing shifts just before cutoff.
    // This carries over consecutive-night and rest-day constraints across the boundary.
    const priorState = await buildPriorState(batch.policyId, cutoff, timeSlots, policy.timezone);

    const newShifts = generateShifts(
      { ...policy, timeSlots },
      participants,
      fromDate,
      batch.rangeEnd,
      startingIndex,
      { policyId: batch.policyId, occupied, priorState }
    ).filter((s) => s.startsAt >= cutoff);

    // Execute in transaction
    await prisma.$transaction(async (tx) => {
      if (removeIds.length > 0) {
        // Cancel open swap requests referencing these shifts
        await tx.swapRequest.updateMany({
          where: {
            status: { in: [SwapStatus.REQUESTED, SwapStatus.ACCEPTED_BY_TARGET] },
            OR: [
              { originalShiftId: { in: removeIds } },
              { targetShiftId: { in: removeIds } },
            ],
          },
          data: { status: SwapStatus.CANCELLED, version: { increment: 1 } },
        });

        // Delete confirmations, tasks, then shifts
        await tx.shiftConfirmation.deleteMany({ where: { shiftId: { in: removeIds } } });
        await tx.shiftTask.deleteMany({ where: { shiftId: { in: removeIds } } });
        await tx.shift.deleteMany({ where: { id: { in: removeIds } } });
      }

      // Create new shifts
      await tx.shift.createMany({
        data: newShifts.map((s) => ({
          policyId: batch.policyId,
          batchId,
          assigneeId: s.assigneeId,
          backupId: s.backupId,
          startsAt: s.startsAt,
          endsAt: s.endsAt,
          status: ShiftStatus.PUBLISHED,
          source: ShiftSource.AUTOGENERATED,
        })),
      });
    });

    // Create confirmations for new shifts
    const createdShifts = await prisma.shift.findMany({
      where: {
        batchId,
        startsAt: { gte: cutoff },
        status: ShiftStatus.PUBLISHED,
      },
      select: { id: true, assigneeId: true, startsAt: true, endsAt: true },
    });

    const minDueAt = new Date(now.getTime() + 60 * 60 * 1000);
    await prisma.shiftConfirmation.createMany({
      data: createdShifts.map((s) => {
        const computed = computeConfirmationDueAt(
          { assigneeId: s.assigneeId, startsAt: s.startsAt, endsAt: s.endsAt },
          policy.confirmationDueHours
        );
        return {
          shiftId: s.id,
          userId: s.assigneeId,
          dueAt: computed < minDueAt ? minDueAt : computed,
        };
      }),
    });

    // Schedule reminders
    const confirmations = await prisma.shiftConfirmation.findMany({
      where: { shift: { batchId, startsAt: { gte: cutoff } } },
      include: { shift: { select: { startsAt: true, endsAt: true } } },
    });

    const remindersScheduled = await scheduleAllRemindersForBatchSafe(
      confirmations.map((c) => ({
        id: c.id,
        shiftId: c.shiftId,
        userId: c.userId,
        dueAt: c.dueAt,
        shift: c.shift,
      })),
      policy,
      `batch-reschedule:${batchId}`
    );

    await writeAuditLog({
      actorId: actor.id,
      entityType: "ScheduleBatch",
      entityId: batchId,
      action: "RESCHEDULE",
      newValue: {
        fromDate: cutoff.toISOString(),
        removedShifts: removeIds.length,
        newShifts: newShifts.length,
        remindersScheduled,
      },
      ipAddress: req.headers.get("x-forwarded-for") ?? undefined,
    });

    const assigneeNotifications = await notifyAssigneesScheduleUpdated({
      policyName: policy.name,
      shifts: confirmations.map((c) => ({
        assigneeId: c.userId,
        startsAt: c.shift.startsAt,
        endsAt: c.shift.endsAt,
        confirmationId: c.id,
      })),
      reason: "rescheduled",
    });

    return ok({
      batchId,
      fromDate: cutoff.toISOString(),
      removedShifts: removeIds.length,
      newShifts: newShifts.length,
      remindersScheduled,
      assigneeNotifications,
    });
  } catch (error) {
    return handleError(error);
  }
}

/**
 * Query the last few shifts before `cutoff` for this policy and derive the prior
 * assignment state (consecutive-night and rest-day tracking).
 */
async function buildPriorState(
  policyId: string,
  cutoff: Date,
  timeSlots: TimeSlot[] | null | undefined,
  timezone: string | null | undefined
): Promise<PriorState> {
  if (!timeSlots || timeSlots.length === 0) return {};

  const tz = timezone ?? "Asia/Ho_Chi_Minh";
  const lookback = subDays(cutoff, 3);

  const recentShifts = await prisma.shift.findMany({
    where: {
      policyId,
      source: ShiftSource.AUTOGENERATED,
      status: { in: [ShiftStatus.PUBLISHED, ShiftStatus.ACTIVE, ShiftStatus.COMPLETED] },
      startsAt: { gte: lookback, lt: cutoff },
    },
    select: { assigneeId: true, startsAt: true, endsAt: true },
    orderBy: { startsAt: "asc" },
  });

  if (recentShifts.length === 0) return {};

  const cutoffDayKey = localDayKey(cutoff, tz);

  // Last assignee before cutoff → previousAssigneeId
  const last = recentShifts[recentShifts.length - 1];
  const previousAssigneeId = last.assigneeId;

  // Last night-shift assignee before cutoff → previousNightAssigneeId
  const lastNightShift = [...recentShifts]
    .reverse()
    .find((s) => isNightShiftTime(s.startsAt, s.endsAt, tz));
  const previousNightAssigneeId = lastNightShift?.assigneeId ?? null;

  // Night shift on the day immediately before cutoff (rest-day rule: they skip cutoff day)
  const dayBeforeKey = localDayKey(subDays(cutoff, 1), tz);
  const nightYesterday = recentShifts.find(
    (s) => localDayKey(s.startsAt, tz) === dayBeforeKey && isNightShiftTime(s.startsAt, s.endsAt, tz)
  );
  const lastNightAssigneeId = nightYesterday?.assigneeId ?? null;

  // Night shift two days before cutoff (D+2 rule: they skip the night slot on cutoff day)
  const twoDaysBeforeKey = localDayKey(subDays(cutoff, 2), tz);
  const nightTwoDaysAgo = recentShifts.find(
    (s) =>
      localDayKey(s.startsAt, tz) === twoDaysBeforeKey &&
      isNightShiftTime(s.startsAt, s.endsAt, tz)
  );
  const twoAgoNightAssigneeId = nightTwoDaysAgo?.assigneeId ?? null;

  // Suppress warnings about unused variable
  void cutoffDayKey;

  return {
    previousAssigneeId,
    previousNightAssigneeId,
    lastNightAssigneeId,
    twoAgoNightAssigneeId,
  };
}
