import { differenceInMinutes } from "date-fns";

const DEFAULT_TIMEZONE = "Asia/Ho_Chi_Minh";

const CONFIRMATION_STATUS_LABELS: Record<string, string> = {
  PENDING: "Chờ xác nhận",
  CONFIRMED: "Đã xác nhận",
  DECLINED: "Đã từ chối",
  EXPIRED: "Đã hết hạn",
};

const SHIFT_STATUS_LABELS: Record<string, string> = {
  PUBLISHED: "Đã xuất bản",
  ACTIVE: "Đang trực",
  COMPLETED: "Hoàn thành",
  CANCELLED: "Đã hủy",
};

const SHIFT_SOURCE_LABELS: Record<string, string> = {
  AUTO: "Tự động",
  AUTOGENERATED: "Tự động",
  MANUAL: "Thủ công",
  SWAP: "Đổi ca",
  OVERRIDE: "Override",
};

export type ScheduleExportRow = {
  stt: string;
  startsAt: string;
  endsAt: string;
  duration: string;
  teamName: string;
  policyName: string;
  assigneeName: string;
  backupName: string;
  shiftStatus: string;
  confirmationStatus: string;
  source: string;
  checkInAt: string;
  checkOutAt: string;
  checkInPhotoUrl: string;
  checkOutPhotoUrl: string;
  note: string;
};

export type ScheduleExportShift = {
  startsAt: Date;
  endsAt: Date;
  teamName?: string | null;
  policyName: string;
  assigneeName: string;
  backupName?: string | null;
  status?: string | null;
  confirmationStatus?: string | null;
  source?: string | null;
  note?: string | null;
  checkInAt?: Date | null;
  checkOutAt?: Date | null;
  checkInPhotoPath?: string | null;
  checkOutPhotoPath?: string | null;
};

export const SCHEDULE_EXPORT_HEADERS = [
  "STT",
  "Bắt đầu",
  "Kết thúc",
  "Thời lượng",
  "Nhóm",
  "Chính sách",
  "Người trực",
  "Dự phòng",
  "Trạng thái ca",
  "Xác nhận",
  "Nguồn",
  "Giờ vào ca",
  "Giờ ra ca",
  "Ảnh vào ca",
  "Ảnh ra ca",
  "Ghi chú",
] as const;

function formatDateTime(date: Date, timezone = DEFAULT_TIMEZONE): string {
  return new Intl.DateTimeFormat("vi-VN", {
    timeZone: timezone,
    hour: "2-digit",
    minute: "2-digit",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date);
}

function formatDuration(start: Date, end: Date): string {
  const totalMins = differenceInMinutes(end, start);
  const h = Math.floor(totalMins / 60);
  const m = totalMins % 60;
  if (m === 0) return `${h} giờ`;
  return `${h}g ${m}p`;
}

function toAbsoluteUrl(baseUrl: string | null | undefined, value: string | null | undefined): string {
  if (!value) return "";
  if (/^https?:\/\//i.test(value)) return value;
  if (!baseUrl) return value;
  const normalizedBase = baseUrl.trim().replace(/\/+$/, "");
  const normalizedPath = value.startsWith("/") ? value : `/${value}`;
  return `${normalizedBase}${normalizedPath}`;
}

function csvEscape(value: string): string {
  return `"${value.replace(/"/g, "\"\"")}"`;
}

function htmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function buildScheduleExportRows(
  shifts: ScheduleExportShift[],
  opts?: { timezone?: string; appBaseUrl?: string | null }
): ScheduleExportRow[] {
  const timezone = opts?.timezone ?? DEFAULT_TIMEZONE;
  const appBaseUrl = opts?.appBaseUrl ?? null;

  return shifts.map((shift, index) => ({
    stt: String(index + 1),
    startsAt: formatDateTime(shift.startsAt, timezone),
    endsAt: formatDateTime(shift.endsAt, timezone),
    duration: formatDuration(shift.startsAt, shift.endsAt),
    teamName: shift.teamName ?? "",
    policyName: shift.policyName,
    assigneeName: shift.assigneeName,
    backupName: shift.backupName ?? "",
    shiftStatus: shift.status ? SHIFT_STATUS_LABELS[shift.status] ?? shift.status : "",
    confirmationStatus: shift.confirmationStatus
      ? CONFIRMATION_STATUS_LABELS[shift.confirmationStatus] ?? shift.confirmationStatus
      : "",
    source: shift.source ? SHIFT_SOURCE_LABELS[shift.source] ?? shift.source : "",
    checkInAt: shift.checkInAt ? formatDateTime(shift.checkInAt, timezone) : "",
    checkOutAt: shift.checkOutAt ? formatDateTime(shift.checkOutAt, timezone) : "",
    checkInPhotoUrl: toAbsoluteUrl(appBaseUrl, shift.checkInPhotoPath ?? ""),
    checkOutPhotoUrl: toAbsoluteUrl(appBaseUrl, shift.checkOutPhotoPath ?? ""),
    note: shift.note ?? "",
  }));
}

export function buildScheduleCsvContent(rows: ScheduleExportRow[]): string {
  const lines = [
    SCHEDULE_EXPORT_HEADERS.map(csvEscape).join(","),
    ...rows.map((row) =>
      [
        row.stt,
        row.startsAt,
        row.endsAt,
        row.duration,
        row.teamName,
        row.policyName,
        row.assigneeName,
        row.backupName,
        row.shiftStatus,
        row.confirmationStatus,
        row.source,
        row.checkInAt,
        row.checkOutAt,
        row.checkInPhotoUrl,
        row.checkOutPhotoUrl,
        row.note,
      ]
        .map((cell) => csvEscape(cell))
        .join(",")
    ),
  ];

  return lines.join("\r\n");
}

export function buildScheduleExcelHtml(rows: ScheduleExportRow[]): string {
  const headersHtml = SCHEDULE_EXPORT_HEADERS.map((header) => `<th>${htmlEscape(header)}</th>`).join("");
  const rowsHtml = rows
    .map((row) => {
      const cells = [
        row.stt,
        row.startsAt,
        row.endsAt,
        row.duration,
        row.teamName,
        row.policyName,
        row.assigneeName,
        row.backupName,
        row.shiftStatus,
        row.confirmationStatus,
        row.source,
        row.checkInAt,
        row.checkOutAt,
      ].map((cell) => `<td>${htmlEscape(cell)}</td>`);

      const checkInPhotoCell = row.checkInPhotoUrl
        ? `<td><a href="${htmlEscape(row.checkInPhotoUrl)}">${htmlEscape(row.checkInPhotoUrl)}</a><br/><img src="${htmlEscape(row.checkInPhotoUrl)}" alt="check-in" width="140" /></td>`
        : "<td></td>";
      const checkOutPhotoCell = row.checkOutPhotoUrl
        ? `<td><a href="${htmlEscape(row.checkOutPhotoUrl)}">${htmlEscape(row.checkOutPhotoUrl)}</a><br/><img src="${htmlEscape(row.checkOutPhotoUrl)}" alt="check-out" width="140" /></td>`
        : "<td></td>";

      cells.push(checkInPhotoCell, checkOutPhotoCell, `<td>${htmlEscape(row.note)}</td>`);
      return `<tr>${cells.join("")}</tr>`;
    })
    .join("");

  return `<!DOCTYPE html><html><head><meta charset="UTF-8" /><style>table{border-collapse:collapse}th,td{border:1px solid #cbd5e1;padding:6px 8px;vertical-align:top;font-size:12px;font-family:Arial,sans-serif}th{background:#f8fafc;font-weight:700}img{margin-top:4px;border:1px solid #e2e8f0}</style></head><body><table><thead><tr>${headersHtml}</tr></thead><tbody>${rowsHtml}</tbody></table></body></html>`;
}

