import { describe, expect, it } from "vitest";
import {
  buildScheduleCsvContent,
  buildScheduleExcelHtml,
  buildScheduleExportRows,
  SCHEDULE_EXPORT_HEADERS,
} from "@/lib/schedule/export";

describe("buildScheduleExportRows", () => {
  it("maps shift data to export rows with absolute photo URLs", () => {
    const rows = buildScheduleExportRows(
      [
        {
          startsAt: new Date("2026-05-01T01:00:00.000Z"),
          endsAt: new Date("2026-05-01T09:00:00.000Z"),
          teamName: "SRE",
          policyName: "Primary",
          assigneeName: "Nguyen Van A",
          backupName: "Tran Van B",
          status: "PUBLISHED",
          confirmationStatus: "CONFIRMED",
          source: "AUTOGENERATED",
          checkInAt: new Date("2026-05-01T00:58:00.000Z"),
          checkOutAt: new Date("2026-05-01T09:02:00.000Z"),
          checkInPhotoPath: "/uploads/shift-proofs/s1/in.jpg",
          checkOutPhotoPath: "/uploads/shift-proofs/s1/out.jpg",
          note: "Ca trực bình thường",
        },
      ],
      { appBaseUrl: "https://oncall.example.com" }
    );

    expect(rows).toHaveLength(1);
    expect(rows[0].teamName).toBe("SRE");
    expect(rows[0].shiftStatus).toBe("Đã xuất bản");
    expect(rows[0].confirmationStatus).toBe("Đã xác nhận");
    expect(rows[0].source).toBe("Tự động");
    expect(rows[0].checkInPhotoUrl).toBe("https://oncall.example.com/uploads/shift-proofs/s1/in.jpg");
    expect(rows[0].checkOutPhotoUrl).toBe("https://oncall.example.com/uploads/shift-proofs/s1/out.jpg");
    expect(rows[0].checkInAt.length).toBeGreaterThan(0);
    expect(rows[0].checkOutAt.length).toBeGreaterThan(0);
  });
});

describe("buildScheduleCsvContent", () => {
  it("renders csv with expected headers and photo columns", () => {
    const rows = buildScheduleExportRows([
      {
        startsAt: new Date("2026-05-01T01:00:00.000Z"),
        endsAt: new Date("2026-05-01T09:00:00.000Z"),
        teamName: "Ops",
        policyName: "Backup",
        assigneeName: "User 1",
        checkInPhotoPath: "/uploads/in.jpg",
        checkOutPhotoPath: "/uploads/out.jpg",
      },
    ]);

    const csv = buildScheduleCsvContent(rows);
    expect(csv).toContain(`"${SCHEDULE_EXPORT_HEADERS[0]}"`);
    expect(csv).toContain(`"${SCHEDULE_EXPORT_HEADERS[12]}"`);
    expect(csv).toContain(`"${SCHEDULE_EXPORT_HEADERS[13]}"`);
    expect(csv).toContain("/uploads/in.jpg");
    expect(csv).toContain("/uploads/out.jpg");
  });
});

describe("buildScheduleExcelHtml", () => {
  it("renders html table with image preview cells", () => {
    const rows = buildScheduleExportRows([
      {
        startsAt: new Date("2026-05-01T01:00:00.000Z"),
        endsAt: new Date("2026-05-01T09:00:00.000Z"),
        policyName: "Primary",
        assigneeName: "User 1",
        checkInPhotoPath: "https://oncall.example.com/in.jpg",
        checkOutPhotoPath: "https://oncall.example.com/out.jpg",
      },
    ]);

    const html = buildScheduleExcelHtml(rows);
    expect(html).toContain("<table>");
    expect(html).toContain("https://oncall.example.com/in.jpg");
    expect(html).toContain('alt="check-in"');
    expect(html).toContain('alt="check-out"');
  });
});
