import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getSessionUser, requireTeamRole, isNextResponse } from "@/lib/rbac";
import {
  created,
  unauthorized,
  badRequest,
  conflict,
  notFound,
  handleError,
} from "@/lib/api-response";
import { ShiftStatus, ShiftSource, TeamRole } from "@/app/generated/prisma/client";
import { generateShifts, computeConfirmationDueAt, TimeSlot, OccupiedMap } from "@/lib/rotation/engine";
import { writeAuditLog } from "@/lib/audit";
import { scheduleAllRemindersForBatchSafe } from "@/lib/queue/scheduler";
import { notifyTeamChannels } from "@/lib/notifications/notify-channel";
import { rateLimit, RATE_LIMITS } from "@/lib/rate-limit";
import { addWeeks } from "date-fns";

const PublishSchema = z.object({
  policyId: z.string().uuid(),
  rangeStart: z.string().datetime(),
  rangeEnd: z.string().datetime().optional(),
  weeks: z.number().int().min(1).max(52).optional(),
});

export async function POST(req: NextRequest) {
  const limited = await rateLimit(req, RATE_LIMITS.WRITE);
  if (limited) return limited;

  const idempotencyKey = req.headers.get("Idempotency-Key");
  if (!idempotencyKey) {
    return badRequest("Idempotency-Key header is required");
  }

  try {
    const actor = await getSessionUser();
    if (!actor) return unauthorized();

    const body = await req.json();
    const data = PublishSchema.parse(body);

    // Idempotency: return existing batch if key already used
    const existing = await prisma.scheduleBatch.findUnique({
      where: { idempotencyKey },
    });
    if (existing) {
      return created(existing);
    }

    const policy = await prisma.rotationPolicy.findUnique({
      where: { id: data.policyId },
      include: {
        team: {
          include: {
            members: {
              include: {
                user: { select: { id: true } },
              },
              orderBy: { order: "asc" },
            },
          },
        },
      },
    });

    if (!policy) return notFound("Policy not found");
    if (!policy.isActive) {
      return conflict("Policy is inactive. Reactivate or create a new policy.", "POLICY_INACTIVE");
    }

    const result = await requireTeamRole(policy.teamId, TeamRole.MANAGER);
    if (isNextResponse(result)) return result;

    if (policy.team.members.length === 0) {
      return badRequest("Team has no members to assign shifts to");
    }

    const rangeStart = new Date(data.rangeStart);
    const rangeEnd = data.rangeEnd
      ? new Date(data.rangeEnd)
      : addWeeks(rangeStart, data.weeks ?? policy.maxGenerateWeeks);

    if (rangeEnd <= rangeStart) {
      return badRequest("rangeEnd must be after rangeStart");
    }

    // Check for overlapping published batch on the same policy
    const overlap = await prisma.scheduleBatch.findFirst({
      where: {
        policyId: data.policyId,
        status: "PUBLISHED",
        rangeStart: { lt: rangeEnd },
        rangeEnd: { gt: rangeStart },
      },
    });
    if (overlap) {
      return conflict(
        "A published batch overlaps the requested date range. Roll it back first.",
        "BATCH_OVERLAP"
      );
    }

    // Backup = next person in rotation order
    const participants = policy.team.members.map((m, i, arr) => ({
      userId: m.user.id,
      backupId: arr[(i + 1) % arr.length].user.id,
    }));

    // Continue rotation from where last batch left off
    const previousShiftCount = await prisma.shift.count({
      where: {
        policyId: data.policyId,
        source: ShiftSource.AUTOGENERATED,
        status: { notIn: [ShiftStatus.CANCELLED] },
      },
    });
    const timeSlots = policy.timeSlots as TimeSlot[] | null | undefined;
    const slotsPerDay = timeSlots && timeSlots.length > 0 ? timeSlots.length : 1;
    // For time-slot mode, rotation advances 1 position per day (not per shift),
    // so startingIndex = number of previously scheduled days % participants.
    // For non-time-slot mode, it advances per shift as before.
    const startingIndex = participants.length > 0
      ? timeSlots && timeSlots.length > 0
        ? Math.floor(previousShiftCount / slotsPerDay) % participants.length
        : previousShiftCount % participants.length
      : 0;

    // Build occupied map: existing shifts from OTHER policies in the same team
    // Used to skip participants who would violate the cross-policy constraint.
    const userIds = participants.map((p) => p.userId);
    const crossPolicyShifts = await prisma.shift.findMany({
      where: {
        policyId: { not: data.policyId },
        policy: { teamId: policy.teamId },
        assigneeId: { in: userIds },
        status: { in: [ShiftStatus.PUBLISHED, ShiftStatus.ACTIVE] },
        startsAt: { lt: rangeEnd },
        endsAt: { gt: rangeStart },
      },
      select: { assigneeId: true, policyId: true, startsAt: true, endsAt: true },
    });

    const occupied: OccupiedMap = new Map();
    for (const s of crossPolicyShifts) {
      const list = occupied.get(s.assigneeId) ?? [];
      list.push({ policyId: s.policyId, startsAt: s.startsAt, endsAt: s.endsAt });
      occupied.set(s.assigneeId, list);
    }

    const generatedShifts = generateShifts(
      { ...policy, timeSlots },
      participants,
      rangeStart,
      rangeEnd,
      startingIndex,
      { policyId: data.policyId, occupied }
    );

    // Create batch + shifts + confirmations in a single transaction
    const batch = await prisma.$transaction(async (tx) => {
      const newBatch = await tx.scheduleBatch.create({
        data: {
          policyId: data.policyId,
          publishedBy: actor.id,
          rangeStart,
          rangeEnd,
          idempotencyKey,
        },
      });

      await tx.shift.createMany({
        data: generatedShifts.map((s) => ({
          policyId: data.policyId,
          batchId: newBatch.id,
          assigneeId: s.assigneeId,
          backupId: s.backupId,
          startsAt: s.startsAt,
          endsAt: s.endsAt,
          status: ShiftStatus.PUBLISHED,
          source: ShiftSource.AUTOGENERATED,
        })),
      });

      // Create confirmations for each shift
      const createdShifts = await tx.shift.findMany({
        where: { batchId: newBatch.id },
        select: { id: true, assigneeId: true, startsAt: true, endsAt: true },
      });

      const batchCreatedAt = new Date();
      const minDueAt = new Date(batchCreatedAt.getTime() + 60 * 60 * 1000); // at least 1h from now
      await tx.shiftConfirmation.createMany({
        data: createdShifts.map((s) => {
          const computed = computeConfirmationDueAt(
            { assigneeId: s.assigneeId, startsAt: s.startsAt, endsAt: s.endsAt },
            policy.confirmationDueHours
          );
          return {
            shiftId: s.id,
            userId: s.assigneeId,
            dueAt: computed < minDueAt ? minDueAt : computed,
          };
        }),
      });

      const tasks = (policy as any).templateTasks as string[];
      if (tasks && tasks.length > 0) {
        await tx.shiftTask.createMany({
          data: createdShifts.flatMap((s) =>
            tasks.map((title, order) => ({ shiftId: s.id, title, order }))
          ),
        });
      }

      return newBatch;
    });

    // Fetch confirmations to schedule reminders
    const confirmations = await prisma.shiftConfirmation.findMany({
      where: { shift: { batchId: batch.id } },
      include: { shift: { select: { startsAt: true, endsAt: true } } },
    });

    const remindersScheduled = await scheduleAllRemindersForBatchSafe(
      confirmations.map((c) => ({
        id: c.id,
        shiftId: c.shiftId,
        userId: c.userId,
        dueAt: c.dueAt,
        shift: c.shift,
      })),
      policy,
      `publish-batch:${batch.id}`
    );

    await writeAuditLog({
      actorId: actor.id,
      entityType: "ScheduleBatch",
      entityId: batch.id,
      action: "PUBLISH",
      newValue: { policyId: data.policyId, rangeStart, rangeEnd, shiftCount: generatedShifts.length },
      ipAddress: req.headers.get("x-forwarded-for") ?? undefined,
    });

    // Notify team Telegram channels that a new schedule has been published
    notifyTeamChannels({
      teamId: policy.teamId,
      eventType: "SCHEDULE_PUBLISHED",
      templateId: "schedule-published",
      recipientId: actor.id,
      variables: {
        actorName: actor.fullName,
        policyName: policy.name,
        shiftCount: generatedShifts.length.toString(),
        rangeStart: rangeStart.toISOString(),
        rangeEnd: rangeEnd.toISOString(),
        appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "",
      },
    }).catch((e) => console.error("notify team channels failed:", e));

    return created({
      ...batch,
      remindersScheduled,
    });
  } catch (error) {
    return handleError(error);
  }
}
