-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- CreateEnum
CREATE TYPE "SystemRole" AS ENUM ('ADMIN', 'USER');

-- CreateEnum
CREATE TYPE "TeamRole" AS ENUM ('MANAGER', 'MEMBER');

-- CreateEnum
CREATE TYPE "ChannelType" AS ENUM ('EMAIL', 'TEAMS', 'TELEGRAM');

-- CreateEnum
CREATE TYPE "ShiftStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ACTIVE', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ShiftSource" AS ENUM ('AUTOGENERATED', 'MANUAL', 'SWAP', 'OVERRIDE');

-- CreateEnum
CREATE TYPE "CadenceKind" AS ENUM ('DAILY', 'WEEKLY', 'CUSTOM_CRON');

-- CreateEnum
CREATE TYPE "ConfirmationStatus" AS ENUM ('PENDING', 'CONFIRMED', 'DECLINED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "SwapStatus" AS ENUM ('REQUESTED', 'ACCEPTED_BY_TARGET', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "DeliveryStatus" AS ENUM ('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'RETRYING', 'CANCELLED');

-- CreateEnum
CREATE TYPE "EscalationTarget" AS ENUM ('PRIMARY', 'BACKUP', 'MANAGER', 'TEAM_CHANNEL');

-- CreateEnum
CREATE TYPE "BatchStatus" AS ENUM ('PUBLISHED', 'ROLLED_BACK', 'PARTIAL');

-- CreateTable accounts (Auth.js)
CREATE TABLE "accounts" (
    "id" TEXT NOT NULL,
    "userId" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable sessions (Auth.js)
CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" UUID NOT NULL,
    "expires" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable verification_tokens (Auth.js)
CREATE TABLE "verification_tokens" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMPTZ NOT NULL
);

-- CreateTable users
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "keycloak_id" TEXT,
    "telegram_chat_id" BIGINT,
    "teams_user_id" TEXT,
    "teams_conversation_id" TEXT,
    "system_role" "SystemRole" NOT NULL DEFAULT 'USER',
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable teams
CREATE TABLE "teams" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "slack_channel" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable team_members
CREATE TABLE "team_members" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "team_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "TeamRole" NOT NULL DEFAULT 'MEMBER',
    "order" INTEGER NOT NULL DEFAULT 0,
    "joined_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "team_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable rotation_policies
CREATE TABLE "rotation_policies" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "team_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "cadence" "CadenceKind" NOT NULL,
    "cron_expression" TEXT,
    "shift_duration_hours" INTEGER NOT NULL,
    "handover_offset_minutes" INTEGER NOT NULL DEFAULT 0,
    "confirmation_due_hours" INTEGER NOT NULL DEFAULT 24,
    "reminder_lead_hours" INTEGER[] DEFAULT ARRAY[24, 2],
    "max_generate_weeks" INTEGER NOT NULL DEFAULT 4,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "rotation_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable schedule_batches
CREATE TABLE "schedule_batches" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "policy_id" UUID NOT NULL,
    "published_by" UUID NOT NULL,
    "range_start" TIMESTAMPTZ NOT NULL,
    "range_end" TIMESTAMPTZ NOT NULL,
    "status" "BatchStatus" NOT NULL DEFAULT 'PUBLISHED',
    "idempotency_key" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "schedule_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable shifts
CREATE TABLE "shifts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "policy_id" UUID NOT NULL,
    "batch_id" UUID,
    "assignee_id" UUID NOT NULL,
    "backup_id" UUID,
    "starts_at" TIMESTAMPTZ NOT NULL,
    "ends_at" TIMESTAMPTZ NOT NULL,
    "status" "ShiftStatus" NOT NULL DEFAULT 'DRAFT',
    "source" "ShiftSource" NOT NULL DEFAULT 'AUTOGENERATED',
    "version" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "shifts_pkey" PRIMARY KEY ("id")
);

-- CreateTable shift_confirmations
CREATE TABLE "shift_confirmations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "shift_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "status" "ConfirmationStatus" NOT NULL DEFAULT 'PENDING',
    "due_at" TIMESTAMPTZ NOT NULL,
    "responded_at" TIMESTAMPTZ,
    "token" TEXT NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "shift_confirmations_pkey" PRIMARY KEY ("id")
);

-- CreateTable swap_requests
CREATE TABLE "swap_requests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "requester_id" UUID NOT NULL,
    "target_user_id" UUID NOT NULL,
    "original_shift_id" UUID NOT NULL,
    "target_shift_id" UUID,
    "status" "SwapStatus" NOT NULL DEFAULT 'REQUESTED',
    "requester_note" TEXT,
    "target_note" TEXT,
    "manager_note" TEXT,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "idempotency_key" TEXT,
    "version" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "swap_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable team_notification_channels
CREATE TABLE "team_notification_channels" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "team_id" UUID NOT NULL,
    "type" "ChannelType" NOT NULL,
    "name" TEXT NOT NULL,
    "config_json" JSONB NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "team_notification_channels_pkey" PRIMARY KEY ("id")
);

-- CreateTable notification_messages
CREATE TABLE "notification_messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "shift_id" UUID,
    "swap_request_id" UUID,
    "recipient_id" UUID NOT NULL,
    "channel_type" "ChannelType" NOT NULL,
    "event_type" TEXT NOT NULL,
    "template_id" TEXT NOT NULL,
    "payload_json" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "notification_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable notification_deliveries
CREATE TABLE "notification_deliveries" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "message_id" UUID NOT NULL,
    "channel_type" "ChannelType" NOT NULL,
    "status" "DeliveryStatus" NOT NULL DEFAULT 'QUEUED',
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "last_attempt_at" TIMESTAMPTZ,
    "external_id" TEXT,
    "error_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "notification_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable escalation_rules
CREATE TABLE "escalation_rules" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "policy_id" UUID NOT NULL,
    "step_order" INTEGER NOT NULL,
    "target" "EscalationTarget" NOT NULL,
    "delay_minutes" INTEGER NOT NULL,
    "channel_type" "ChannelType" NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "escalation_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable audit_logs
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "actor_id" UUID,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "old_value" JSONB,
    "new_value" JSONB,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- Unique constraints
CREATE UNIQUE INDEX "accounts_provider_providerAccountId_key" ON "accounts"("provider", "providerAccountId");
CREATE UNIQUE INDEX "sessions_sessionToken_key" ON "sessions"("sessionToken");
CREATE UNIQUE INDEX "verification_tokens_token_key" ON "verification_tokens"("token");
CREATE UNIQUE INDEX "verification_tokens_identifier_token_key" ON "verification_tokens"("identifier", "token");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_keycloak_id_key" ON "users"("keycloak_id");
CREATE UNIQUE INDEX "teams_name_key" ON "teams"("name");
CREATE UNIQUE INDEX "team_members_team_id_user_id_key" ON "team_members"("team_id", "user_id");
CREATE UNIQUE INDEX "schedule_batches_idempotency_key_key" ON "schedule_batches"("idempotency_key");
CREATE UNIQUE INDEX "shift_confirmations_shift_id_key" ON "shift_confirmations"("shift_id");
CREATE UNIQUE INDEX "shift_confirmations_token_key" ON "shift_confirmations"("token");
CREATE UNIQUE INDEX "swap_requests_idempotency_key_key" ON "swap_requests"("idempotency_key");
CREATE UNIQUE INDEX "team_notification_channels_team_id_type_name_key" ON "team_notification_channels"("team_id", "type", "name");
CREATE UNIQUE INDEX "escalation_rules_policy_id_step_order_key" ON "escalation_rules"("policy_id", "step_order");

-- Performance indexes
CREATE INDEX "shifts_policy_id_starts_at_ends_at_idx" ON "shifts"("policy_id", "starts_at", "ends_at");
CREATE INDEX "shifts_assignee_id_starts_at_idx" ON "shifts"("assignee_id", "starts_at");
CREATE INDEX "shifts_status_idx" ON "shifts"("status");
CREATE INDEX "swap_requests_requester_id_status_idx" ON "swap_requests"("requester_id", "status");
CREATE INDEX "swap_requests_target_user_id_status_idx" ON "swap_requests"("target_user_id", "status");
CREATE INDEX "notification_messages_shift_id_idx" ON "notification_messages"("shift_id");
CREATE INDEX "notification_messages_recipient_id_created_at_idx" ON "notification_messages"("recipient_id", "created_at");
CREATE INDEX "notification_deliveries_status_channel_type_idx" ON "notification_deliveries"("status", "channel_type");
CREATE INDEX "audit_logs_entity_type_entity_id_idx" ON "audit_logs"("entity_type", "entity_id");
CREATE INDEX "audit_logs_actor_id_created_at_idx" ON "audit_logs"("actor_id", "created_at");

-- Foreign key constraints
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "rotation_policies" ADD CONSTRAINT "rotation_policies_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "schedule_batches" ADD CONSTRAINT "schedule_batches_policy_id_fkey" FOREIGN KEY ("policy_id") REFERENCES "rotation_policies"("id") ON UPDATE CASCADE;
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_policy_id_fkey" FOREIGN KEY ("policy_id") REFERENCES "rotation_policies"("id") ON UPDATE CASCADE;
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "schedule_batches"("id") ON UPDATE CASCADE;
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON UPDATE CASCADE;
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_backup_id_fkey" FOREIGN KEY ("backup_id") REFERENCES "users"("id") ON UPDATE CASCADE;
ALTER TABLE "shift_confirmations" ADD CONSTRAINT "shift_confirmations_shift_id_fkey" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "shift_confirmations" ADD CONSTRAINT "shift_confirmations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON UPDATE CASCADE;
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_requester_id_fkey" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON UPDATE CASCADE;
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_target_user_id_fkey" FOREIGN KEY ("target_user_id") REFERENCES "users"("id") ON UPDATE CASCADE;
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_original_shift_id_fkey" FOREIGN KEY ("original_shift_id") REFERENCES "shifts"("id") ON UPDATE CASCADE;
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_target_shift_id_fkey" FOREIGN KEY ("target_shift_id") REFERENCES "shifts"("id") ON UPDATE CASCADE;
ALTER TABLE "team_notification_channels" ADD CONSTRAINT "team_notification_channels_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notification_deliveries" ADD CONSTRAINT "notification_deliveries_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "notification_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
