import { NextRequest } from "next/server";
import { startOfDay } from "date-fns";
import { prisma } from "@/lib/prisma";
import { getSessionUser, requireTeamRole, isNextResponse } from "@/lib/rbac";
import { ok, unauthorized, notFound, conflict, badRequest, handleError } from "@/lib/api-response";
import { BatchStatus, ShiftStatus, ShiftSource, SwapStatus, TeamRole } from "@/app/generated/prisma/client";
import { generateShifts, computeConfirmationDueAt, TimeSlot } from "@/lib/rotation/engine";
import { scheduleAllRemindersForBatch } from "@/lib/queue/scheduler";
import { writeAuditLog } from "@/lib/audit";

// POST /api/policies/[id]/reschedule-from-now
// Finds the active PUBLISHED batch for this policy and regenerates all future shifts
// from today onward using the current policy config and team roster.
// Called automatically after policy edits so the schedule reflects the new settings.
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const actor = await getSessionUser();
    if (!actor) return unauthorized();

    const { id: policyId } = await params;

    const policy = await prisma.rotationPolicy.findUnique({
      where: { id: policyId },
      include: {
        team: {
          include: {
            members: {
              include: { user: { select: { id: true } } },
              orderBy: { order: "asc" },
            },
          },
        },
      },
    });
    if (!policy) return notFound("Policy not found");

    const roleCheck = await requireTeamRole(policy.teamId, TeamRole.MANAGER);
    if (isNextResponse(roleCheck)) return roleCheck;

    if (policy.team.members.length === 0) {
      return badRequest("Nhóm chưa có thành viên nào");
    }

    // Find the most recent PUBLISHED batch for this policy
    const batch = await prisma.scheduleBatch.findFirst({
      where: { policyId, status: BatchStatus.PUBLISHED },
      orderBy: { createdAt: "desc" },
    });

    if (!batch) {
      return conflict(
        "Chưa có lô lịch nào được xuất bản. Hãy sinh lịch trước rồi chỉnh sửa.",
        "NO_PUBLISHED_BATCH"
      );
    }

    const now = new Date();
    // Use start of today (server UTC) as the cut point — do NOT clamp to
    // batch.rangeStart. If the batch starts tomorrow (midnight local), clamping
    // would push fromDate past today's shifts and leave them unreplaced.
    const fromDate = startOfDay(now);

    if (fromDate >= batch.rangeEnd) {
      return conflict(
        "Lô lịch hiện tại đã hết hạn. Hãy sinh lô lịch mới.",
        "BATCH_EXPIRED"
      );
    }

    // Block only if a shift starting AFTER RIGHT NOW (across ALL batches for
    // this policy) is already ACTIVE or COMPLETED. We use `now` so a currently-
    // running shift that started earlier today doesn't block the reschedule —
    // it's ACTIVE but won't be deleted because the delete query filters PUBLISHED only.
    const blockedCount = await prisma.shift.count({
      where: {
        policyId,
        startsAt: { gte: now },
        status: { in: [ShiftStatus.ACTIVE, ShiftStatus.COMPLETED] },
      },
    });
    if (blockedCount > 0) {
      return conflict(
        `Có ${blockedCount} ca đang diễn ra hoặc đã hoàn thành. Không thể tạo lại.`,
        "SHIFTS_ACTIVE"
      );
    }

    const participants = policy.team.members.map((m, i, arr) => ({
      userId: m.user.id,
      backupId: arr[(i + 1) % arr.length].user.id,
    }));

    const timeSlots = policy.timeSlots as TimeSlot[] | null | undefined;

    // Continue rotation from correct position: count kept shifts before fromDate
    const keptShiftCount = await prisma.shift.count({
      where: {
        policyId,
        source: ShiftSource.AUTOGENERATED,
        status: { notIn: [ShiftStatus.CANCELLED] },
        startsAt: { lt: fromDate },
      },
    });

    const slotsPerDay = timeSlots && timeSlots.length > 0 ? timeSlots.length : 1;
    const startingIndex =
      timeSlots && timeSlots.length > 0
        ? Math.floor(keptShiftCount / slotsPerDay) % participants.length
        : keptShiftCount % participants.length;

    // Generate from start-of-today so the engine covers today's full day slots,
    // but only keep shifts that start at or after NOW to avoid creating PUBLISHED
    // duplicates of shifts that are already ACTIVE or have already passed today.
    const newShifts = generateShifts(
      { ...policy, timeSlots },
      participants,
      fromDate,      // rangeStart = midnight — engine needs full-day coverage
      batch.rangeEnd,
      startingIndex
    ).filter((s) => s.startsAt >= now);

    // Delete PUBLISHED shifts starting from NOW onwards (not midnight) across ALL
    // batches for this policy. Using policyId catches orphaned shifts from old or
    // rolled-back batches. Using `now` avoids touching shifts that have already
    // started (they'd be ACTIVE anyway, but belt-and-suspenders).
    const shiftsToRemove = await prisma.shift.findMany({
      where: { policyId, startsAt: { gte: now }, status: ShiftStatus.PUBLISHED },
      select: { id: true },
    });
    const removeIds = shiftsToRemove.map((s) => s.id);

    await prisma.$transaction(async (tx) => {
      if (removeIds.length > 0) {
        // Cancel open swap requests referencing these shifts
        await tx.swapRequest.updateMany({
          where: {
            status: { in: [SwapStatus.REQUESTED, SwapStatus.ACCEPTED_BY_TARGET] },
            OR: [
              { originalShiftId: { in: removeIds } },
              { targetShiftId: { in: removeIds } },
            ],
          },
          data: { status: SwapStatus.CANCELLED, version: { increment: 1 } },
        });

        await tx.shiftConfirmation.deleteMany({ where: { shiftId: { in: removeIds } } });
        await tx.shiftTask.deleteMany({ where: { shiftId: { in: removeIds } } });
        await tx.shift.deleteMany({ where: { id: { in: removeIds } } });
      }

      await tx.shift.createMany({
        data: newShifts.map((s) => ({
          policyId,
          batchId: batch.id,
          assigneeId: s.assigneeId,
          backupId: s.backupId,
          startsAt: s.startsAt,
          endsAt: s.endsAt,
          status: ShiftStatus.PUBLISHED,
          source: ShiftSource.AUTOGENERATED,
        })),
      });
    });

    // Create confirmations for new shifts
    const createdShifts = await prisma.shift.findMany({
      where: { batchId: batch.id, startsAt: { gte: now }, status: ShiftStatus.PUBLISHED },
      select: { id: true, assigneeId: true, startsAt: true, endsAt: true },
    });

    const minDueAt = new Date(Date.now() + 60 * 60 * 1000);
    await prisma.shiftConfirmation.createMany({
      data: createdShifts.map((s) => {
        const computed = computeConfirmationDueAt(
          { assigneeId: s.assigneeId, startsAt: s.startsAt, endsAt: s.endsAt },
          policy.confirmationDueHours
        );
        return {
          shiftId: s.id,
          userId: s.assigneeId,
          dueAt: computed < minDueAt ? minDueAt : computed,
        };
      }),
    });

    // Schedule reminders
    const confirmations = await prisma.shiftConfirmation.findMany({
      where: { shift: { batchId: batch.id, startsAt: { gte: now } } },
      include: { shift: { select: { startsAt: true, endsAt: true } } },
    });

    await scheduleAllRemindersForBatch(
      confirmations.map((c) => ({
        id: c.id,
        shiftId: c.shiftId,
        userId: c.userId,
        dueAt: c.dueAt,
        shift: c.shift,
      })),
      policy
    );

    await writeAuditLog({
      actorId: actor.id,
      entityType: "RotationPolicy",
      entityId: policyId,
      action: "RESCHEDULE_FROM_NOW",
      newValue: {
        batchId: batch.id,
        fromDate: fromDate.toISOString(),
        removedShifts: removeIds.length,
        newShifts: newShifts.length,
      },
      ipAddress: req.headers.get("x-forwarded-for") ?? undefined,
    });

    return ok({
      batchId: batch.id,
      fromDate: fromDate.toISOString(),
      removedShifts: removeIds.length,
      newShifts: newShifts.length,
    });
  } catch (error) {
    return handleError(error);
  }
}
